import { supabase } from "@/integrations/supabase/client";

export interface AddPatientResult {
  tokenNumber: number;
  trackingCode: string;
}

export function useAddPatient() {
  const addPatient = async (name: string, phone: string, doctorId: string, userId?: string): Promise<AddPatientResult> => {
    // Get the next token number for today
    const { data: tokenNumber, error: tErr } = await supabase.rpc("next_token_number", { p_doctor_id: doctorId });
    if (tErr) {
      console.error("[useAddPatient] next_token_number RPC failed:", tErr.message, tErr.code, tErr.details);
      throw new Error(`Token generation failed: ${tErr.message}`);
    }

    // Insert into queue_entries (tracking_code is auto-generated by the DB trigger)
    const { data: inserted, error } = await supabase.from("queue_entries").insert({
      token_number: tokenNumber as number,
      patient_name: name,
      phone,
      status: "waiting" as const,
      user_id: userId || null,
      doctor_id: doctorId,
    }).select("token_number, tracking_code").single();

    if (error) {
      console.error("[useAddPatient] queue_entries insert failed:", error.message, error.code, error.details);
      throw new Error(`Could not add patient: ${error.message}`);
    }

    if (phone.trim()) {
      try {
        const { data: existingPatient } = await supabase
          .from("patients")
          .select("id, visit_count")
          .eq("phone", phone.trim())
          .maybeSingle();

        if (existingPatient) {
          await supabase
            .from("patients")
            .update({
              name,
              last_visit_date: new Date().toISOString().split("T")[0],
              preferred_doctor_id: doctorId,
              visit_count: (existingPatient.visit_count || 1) + 1,
              updated_at: new Date().toISOString(),
            })
            .eq("id", existingPatient.id);
        } else {
          await supabase
            .from("patients")
            .insert({
              name,
              phone: phone.trim(),
              last_visit_date: new Date().toISOString().split("T")[0],
              preferred_doctor_id: doctorId,
              visit_count: 1,
            });
        }
      } catch (err) {
        console.error("Patient registry upsert failed, ignoring...", err);
      }
    }

    return {
      tokenNumber: inserted.token_number,
      trackingCode: inserted.tracking_code ?? `${inserted.token_number}`,
    };
  };

  return { addPatient };
}
